### PR TITLE
Create CSS Guidelines

### PR DESCRIPTION
**Pull request by Luke-Cutter**
Add this into the main branch. Give me suggestions of guidelines to add, I thought these were the most pertinent!

### CODE REVIEW

**Comment by landishumphrey** [comment]
So, this is the rulebook for the website's design?

**Comment by mkerwoodchamp** [comment]
I suggest a small change of putting what the colors are in addition to the hex color codes so that people looking at it know the colors because I don't think everyone would know the color based on the code.

**Comment by Luke-Cutter** [comment]
> I suggest a small change of putting what the colors are in addition to the hex color codes so that people looking at it know the colors because I don't think everyone would know the color based on the code.

Makes sense, will do!

**Review by Luke-Cutter — COMMENTED** [review]
Made the changes requested

**Review by mkerwoodchamp — APPROVED** [review]

**Pull request merged**
